version: '1.0.{build}'

test_script:
  - cmd: ECHO this is batch
  - ps: Write-Host "This is PowerShell"

on_success:
  - ps: |
      if ($true)
      {
        Write-Host "Success"
      }